live_config_reload = true
# =========================================================================
[shell]
program = "/opt/homebrew/bin/fish"
# args = ["-l"]
# =========================================================================
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 13.0
offset = { x = 1, y = 0 }
[window]
padding = { x = 10, y = 10 }
decorations = "Full" # need restart
opacity = 0.7
blur = true
# =========================================================================
[colors]
# Default colors
[colors.primary]
background = '#2c2c2c'
foreground = '#d6d6d6'

dim_foreground    = '#dbdbdb'
bright_foreground = '#d9d9d9'

# Cursor colors
[colors.cursor]
text = "0xF7F9F9"
cursor = "0x45B39D"

# Normal colors
[colors.normal]
black   = '#1c1c1c'
red     = '#bc5653'
green   = '#909d63'
yellow  = '#ebc17a'
blue    = '#7eaac7'
magenta = '#aa6292'
cyan    = '#86d3ce'
white   = '#cacaca'

# Bright colors
[colors.bright]
black   = '#636363'
red     = '#bc5653'
green   = '#909d63'
yellow  = '#ebc17a'
blue    = '#7eaac7'
magenta = '#aa6292'
cyan    = '#86d3ce'
white   = '#f7f7f7'

# Dim colors
[colors.dim]
black   = '#232323'
red     = '#74423f'
green   = '#5e6547'
yellow  = '#8b7653'
blue    = '#556b79'
magenta = '#6e4962'
cyan    = '#5c8482'
white   = '#828282'

# =========================================================================
[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.3
blink_interval = 400
blink_timeout = 0 # 不会停止闪烁
# =========================================================================
[keyboard]
bindings = [
    { key = "[", mods = "Command" ,action = "WordLeft", mode="Vi"}
]
